import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/navigation";
import { ConfigurationProvider } from "@/lib/configuration-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "P-Agents",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning style={{ colorScheme: "light", backgroundColor: "white" }}>
      <body className="min-h-full flex flex-col" style={{ backgroundColor: "white", color: "black" }}>
        <Navigation />
        <main className="flex-1">
          <ConfigurationProvider>{children}</ConfigurationProvider>
        </main>
      </body>
    </html>
  );
}
